name: Create Preview Builds

on:
  push:
    tags:
      - "preview*"

jobs:
  build_android:
    name: Build Android Preview
    type: build
    params:
      platform: android
      profile: preview
